# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.FileField(max_length=200, null=True, upload_to=None),
        ),
    ]
