# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_auto_20160302_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.FileField(max_length=200, upload_to=None),
        ),
    ]
